apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  labels:
    app: nextcloud
data:
  NEXTCLOUD_UPDATE: "1"
  ALLOW_EMPTY_PASSWORD: "yes"
  NEXTCLOUD_TRUSTED_DOMAINS: "*"
  POSTGRES_HOST: "postgres-service"